[gcp_service_account]
type = "service_account"
project_id = "streamlit-464310"
private_key_id = "bc58f74666e07653a9e62323447a2e97d72affe9"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9qLWbiguGlFZR
iAqmtUUn/3I90btxH6QOND0+crjiSchUBe/nafKvIm2CQjzXQv8sQlFGJEDogRKh
vQZkJApQ1Fdhor6EOtvECrxM2zkHZlTNA4G45VughRKnz+/u1ThrNqMZc1Qx2q8M
05UOYmeaiPAdAlzoRpwomlvhmSrbSJqaKH3a8l4xjfcTTk4OWdieWgJbsS5BKwIa
O68Gr+uPbO2l/pNMwIEu/mhmbDEvrxtnyVEzfIhWuRaEijCekLHGjHT1oOfO9EzH
hx0oDNwHdXBRCL+VS0R/5Vor7C1+8mCsewOO7rx1zSGWwSY7v04CuksW1HTBUHn6
1yeOCqM7AgMBAAECggEAA+2yMVIXMgbxkMfGHLTlhVITvjcRcGLs5YRsflYnATzx
AtiKoxr9NWZ7qTaRBw5ytap7/31xwL8nsST2tG1Qr2Lumm2iD6AefD2Sr+7cjAwx
FnwLnFZX4wfOnp4+hI5zGDluAHF0nYG/nX7meAFOzxMmEhvB6+fGhUrJO2+ORTN/
KbCnw1YRKziNdbVzW79rLzyq+p4exfKmZIGeGcJ31ezC3CXIEKFBWBMT2QV3V0gd
u5UjfosAP0ht/h88Adu5pYtSN7hLvV6bylIU2aL13j5RFnBDxj9gb5P5V72XcGl2
IiEPbODNRBeR593o0Y3kEFxfbpBWPRI2N3l5c58iwQKBgQDlCC/fU3ITf0EXHfor
Oham5pPe+8ThPRtPqzHoBTCFdt2PYYZ2CZSD5jWyKowXU616qYHn7wXl49DgDmUZ
QpGIXc9+yfz95bao7FaEdnsriCnPD7QGgE8kbVCMG/T2+vCRT9uUYrGszzlpP0q/
ysYLg3BsHnc5MOt5hwoiYJTpQQKBgQDT/a+Ndtf7P8oPJhgPXihtqFaNHYYEBZWe
yq/l3LYR0er3IV3EXNpWnCbsVphG+mBLFu/M5hQ7/s0xjHLzguUi8lCSZyKl/Yq9
bCOleeD8vX4bgKDGkDHWKDDfFqw3vaM6RUvh153e7Bm1PfHKxhQ0ZoCBKaCwIAJR
si95U3FRewKBgHE7T/e4mLCc/IBCWNmgOWzAmKDolpjJDkSgHedZEXkaoEVv8PtQ
lzVyzl9Me8BYpW78ePZDDQZwUGdFlqQbbjoeLyS/Fi4ssNbpKYkJzrFh+1GcsON5
8ibPSMBMXhrxS5h8A9JjzPXj6b1oBju2M52jmSRLF6SV1AVcRx1h5J1BAoGAUjZo
Bqy4RjAO5KEZY5xYgW5vYnq4poaj59kjLjnSQkbuoLjH7Ic2BbC5R56tn5kqDvTu
OsBfyISgfz7Atb9lrY/bv2tP/J+/VobBrEMABgRXC8NulpMFQNCFY38fet6IluiY
7RT5nKJjte43/zOiUlAONgk20BcZzyUTVDIQGFECgYEAutIj5XXX3TB5Jq3alcsR
NIUh63AhqJzsCsRejX2NF6tPRlOUSkWgpzPnNNcJ3vAR24aFFRi9h0AzMb9GHJ4r
GfGntfpKosd7T3N37mOryMubeN0YKH77HcZ7fX7FQaiGbIuzJIGi7U2v9pSF0bOu
+mZabiuPHb03GvKwI3x8XYE=
-----END PRIVATE KEY-----"""
client_email = "streamlit@streamlit-464310.iam.gserviceaccount.com"
client_id = "103805699150780967487"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit%40streamlit-464310.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
